# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False)),
                ('titleAuc', models.CharField(max_length=50)),
                ('deadLine', models.DateTimeField(db_index=True)),
                ('content', models.TextField()),
                ('minPrice', models.FloatField(default=0.0)),
                ('locked', models.TextField(default=b'')),
                ('author', models.TextField(default=b'')),
            ],
        ),
    ]
