# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-18 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('YAASApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2015, 10, 18, 13, 18, 9, 498172, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
