# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAASApp', '0002_auction_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bidder',
            field=models.TextField(default=b''),
        ),
    ]
