# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAASApp', '0004_auction_banded'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='authoremail',
            field=models.TextField(default=b''),
        ),
    ]
