# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAASApp', '0005_auction_authoremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bidderemail',
            field=models.TextField(default=b''),
        ),
    ]
