# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAASApp', '0006_auction_bidderemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='resolve',
            field=models.TextField(default=b''),
        ),
    ]
