# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-31 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAASApp', '0007_auction_resolve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidderName', models.TextField(default=b'')),
                ('bidderEmail', models.TextField(default=b'')),
                ('bidItem', models.IntegerField(default=b'')),
            ],
        ),
    ]
